CREATE TABLE MARKET_CAP_FUND(CAP_ID NUMBER(10),FN_ID NUMBER(10),
CONSTRAINTS FK3_CAP_ID FOREIGN KEY(CAP_ID) REFERENCES MARKET_CAP(CAP_ID) ON DELETE CASCADE,
CONSTRAINTS FK3_ST_ID FOREIGN KEY(FN_ID) REFERENCES FUNDS(FN_ID) ON DELETE CASCADE)

INSERT INTO MARKET_CAP_FUND VALUES('71','200')
INSERT INTO MARKET_CAP_FUND VALUES('82','201')
INSERT INTO MARKET_CAP_FUND VALUES('83','205')
INSERT INTO MARKET_CAP_FUND VALUES('81','207')
INSERT INTO MARKET_CAP_FUND VALUES('79','211')
INSERT INTO MARKET_CAP_FUND VALUES('72','212')
INSERT INTO MARKET_CAP_FUND VALUES('73','214')
INSERT INTO MARKET_CAP_FUND VALUES('72','213')
INSERT INTO MARKET_CAP_FUND VALUES('76','208')