CREATE TABLE MARKET_CAP_STOCKS(CAP_ID NUMBER(10),ST_ID NUMBER(10),
CONSTRAINTS FK2_CAP_ID FOREIGN KEY(CAP_ID) REFERENCES MARKET_CAP ON DELETE CASCADE,
CONSTRAINTS FK2_ST_ID FOREIGN KEY(ST_ID) REFERENCES STOCKS ON DELETE CASCADE)

INSERT INTO MARKET_CAP_STOCKS VALUES('71','100')
INSERT INTO MARKET_CAP_STOCKS VALUES('74','101')
INSERT INTO MARKET_CAP_STOCKS VALUES('77','102')
INSERT INTO MARKET_CAP_STOCKS VALUES('78','103')
INSERT INTO MARKET_CAP_STOCKS VALUES('79','104')
INSERT INTO MARKET_CAP_STOCKS VALUES('81','105')
INSERT INTO MARKET_CAP_STOCKS VALUES('85','106')
INSERT INTO MARKET_CAP_STOCKS VALUES('76','106')
INSERT INTO MARKET_CAP_STOCKS VALUES('70','107')
INSERT INTO MARKET_CAP_STOCKS VALUES('76','114')