CREATE TABLE MARKET_CAP_BONDS(CAP_ID NUMBER(10),BN_ID NUMBER(10),
CONSTRAINTS FK4_CAP_ID FOREIGN KEY(CAP_ID) REFERENCES MARKET_CAP(CAP_ID) ON DELETE CASCADE,
CONSTRAINTS FK4_BN_ID FOREIGN KEY(BN_ID) REFERENCES BONDS(BN_ID) ON DELETE CASCADE)

INSERT INTO MARKET_CAP_BONDS VALUES('77','302')
INSERT INTO MARKET_CAP_BONDS VALUES('78','303')
INSERT INTO MARKET_CAP_BONDS VALUES('80','306')
INSERT INTO MARKET_CAP_BONDS VALUES('81','307')
INSERT INTO MARKET_CAP_BONDS VALUES('83','310')
INSERT INTO MARKET_CAP_BONDS VALUES('84','314')
INSERT INTO MARKET_CAP_BONDS VALUES('85','311')