CREATE TABLE MARKET_CAP_CRYPTO_CURRENCY(CAP_ID NUMBER(10),CC_ID NUMBER(10),
CONSTRAINTS FK5_CAP_ID FOREIGN KEY(CAP_ID) REFERENCES MARKET_CAP(CAP_ID) ON DELETE CASCADE,
CONSTRAINTS FK5_CC_ID FOREIGN KEY(CC_ID) REFERENCES CRYPTO_CURRENCY(CC_ID) ON DELETE CASCADE)
INSERT INTO MARKET_CAP_CRYPTO_CURRENCY VALUES('70','400')
INSERT INTO MARKET_CAP_CRYPTO_CURRENCY VALUES('75','401')
INSERT INTO MARKET_CAP_CRYPTO_CURRENCY VALUES('80','414')
INSERT INTO MARKET_CAP_CRYPTO_CURRENCY VALUES('82','404')
INSERT INTO MARKET_CAP_CRYPTO_CURRENCY VALUES('83','411')
INSERT INTO MARKET_CAP_CRYPTO_CURRENCY VALUES('85','412')